/** Fixed invoice texts per language (UStG §14 wording in German). */
export const LABELS = {
  de: {
    final: "Rechnung",
    deposit: "Anzahlungsrechnung",
    number: "Rechnungsnummer",
    date: "Rechnungsdatum",
    period: "Leistungszeitraum",
    received: "Zahlung erhalten am",
    reference: "Buchung",
    qty: "Menge",
    item: "Leistung",
    unit: "Einzelpreis",
    tax: "USt.",
    amount: "Betrag",
    taxBreakdown: "Umsatzsteuer",
    net: "Netto",
    vat: "USt.",
    gross: "Brutto",
    total: "Gesamtbetrag",
    lessDeposit: "abzüglich Anzahlung {number} vom {date}",
    ofWhichVat: "darin enthaltene USt.",
    paid: "bereits bezahlt",
    due: "Offener Betrag",
    dueBy: "Zahlbar bis {date}",
    settled: "Der Betrag ist beglichen.",
    vatId: "USt-IdNr.",
    taxNumber: "Steuernummer",
    bank: "Bankverbindung",
    depositLine: "Anzahlung für den Aufenthalt",
    page: "Seite",
  },
  en: {
    final: "Invoice",
    deposit: "Deposit invoice",
    number: "Invoice number",
    date: "Invoice date",
    period: "Service period",
    received: "Payment received on",
    reference: "Booking",
    qty: "Qty",
    item: "Service",
    unit: "Unit price",
    tax: "VAT",
    amount: "Amount",
    taxBreakdown: "VAT",
    net: "Net",
    vat: "VAT",
    gross: "Gross",
    total: "Total",
    lessDeposit: "less deposit {number} of {date}",
    ofWhichVat: "of which VAT",
    paid: "already paid",
    due: "Amount due",
    dueBy: "Payable by {date}",
    settled: "The amount has been settled.",
    vatId: "VAT ID",
    taxNumber: "Tax number",
    bank: "Bank details",
    depositLine: "Deposit for the stay",
    page: "Page",
  },
} as const;

export type Labels = (typeof LABELS)["de"];
