/** Fixed invoice texts per language (UStG §14 wording in German). */
export const LABELS = {
  de: {
    final: "Rechnung",
    deposit: "Anzahlungsrechnung",
    cancellation: "Stornorechnung",
    cancels: "Storno zu Rechnung {number} vom {date}",
    reminderTitle1: "Zahlungserinnerung",
    reminderTitle2: "2. Mahnung",
    reminderTitle3: "Letzte Mahnung",
    reminderText1: "sicher ist es Ihrer Aufmerksamkeit entgangen: Für die folgenden Rechnungen haben wir noch keinen Zahlungseingang. Bitte überweisen Sie den offenen Betrag bis zum {date}.",
    reminderText2: "trotz unserer Zahlungserinnerung sind die folgenden Rechnungen weiterhin offen. Bitte überweisen Sie den Betrag bis zum {date}.",
    reminderText3: "die folgenden Rechnungen sind trotz Mahnung weiterhin offen. Wir bitten Sie letztmalig um Zahlung bis zum {date}; danach geben wir die Forderung ohne weitere Ankündigung ab.",
    reminderGreeting: "Sehr geehrte Damen und Herren,",
    reminderClosing: "Hat sich Ihre Zahlung mit diesem Schreiben überschnitten, betrachten Sie es bitte als gegenstandslos.",
    reminderRegards: "Mit freundlichen Grüßen",
    invoiceCol: "Rechnung",
    dueCol: "fällig am",
    openCol: "offen",
    totalOpen: "Offen gesamt",
    number: "Rechnungsnummer",
    date: "Rechnungsdatum",
    period: "Leistungszeitraum",
    received: "Zahlung erhalten am",
    reference: "Buchung",
    qty: "Menge",
    item: "Leistung",
    unit: "Einzelpreis",
    tax: "USt.",
    amount: "Betrag",
    taxBreakdown: "Umsatzsteuer",
    net: "Netto",
    vat: "USt.",
    gross: "Brutto",
    total: "Gesamtbetrag",
    lessDeposit: "abzüglich Anzahlung {number} vom {date}",
    ofWhichVat: "darin enthaltene USt.",
    paid: "bereits bezahlt",
    due: "Offener Betrag",
    dueBy: "Zahlbar bis {date}",
    settled: "Der Betrag ist beglichen.",
    vatId: "USt-IdNr.",
    taxNumber: "Steuernummer",
    bank: "Bankverbindung",
    depositLine: "Anzahlung für den Aufenthalt",
    earlyDepartureFee: "Gebühr für vorzeitige Abreise",
    page: "Seite",
  },
  en: {
    final: "Invoice",
    deposit: "Deposit invoice",
    cancellation: "Cancellation invoice",
    cancels: "Cancels invoice {number} of {date}",
    reminderTitle1: "Payment reminder",
    reminderTitle2: "Second reminder",
    reminderTitle3: "Final reminder",
    reminderText1: "we have not yet received payment for the invoices below. Please transfer the open amount by {date}.",
    reminderText2: "despite our reminder, the invoices below are still open. Please transfer the amount by {date}.",
    reminderText3: "despite our reminders, the invoices below remain unpaid. We ask you for the last time to pay by {date}; after that we will pass the claim on without further notice.",
    reminderGreeting: "Dear Sir or Madam,",
    reminderClosing: "If your payment has crossed with this letter, please disregard it.",
    reminderRegards: "Kind regards",
    invoiceCol: "Invoice",
    dueCol: "due",
    openCol: "open",
    totalOpen: "Total open",
    number: "Invoice number",
    date: "Invoice date",
    period: "Service period",
    received: "Payment received on",
    reference: "Booking",
    qty: "Qty",
    item: "Service",
    unit: "Unit price",
    tax: "VAT",
    amount: "Amount",
    taxBreakdown: "VAT",
    net: "Net",
    vat: "VAT",
    gross: "Gross",
    total: "Total",
    lessDeposit: "less deposit {number} of {date}",
    ofWhichVat: "of which VAT",
    paid: "already paid",
    due: "Amount due",
    dueBy: "Payable by {date}",
    settled: "The amount has been settled.",
    vatId: "VAT ID",
    taxNumber: "Tax number",
    bank: "Bank details",
    depositLine: "Deposit for the stay",
    earlyDepartureFee: "Early departure fee",
    page: "Page",
  },
} as const;

export type Labels = (typeof LABELS)["de"];
