import type { Pool, PoolClient } from "pg";

/**
 * Tenant schema names are generated by us: `t_` followed by lowercase letters,
 * digits and underscores. Anything else is refused before it reaches SQL.
 */
const TENANT_SCHEMA = /^t_[a-z0-9_]{1,50}$/;

export function isTenantSchemaName(name: string): boolean {
  return TENANT_SCHEMA.test(name);
}

export function assertTenantSchemaName(name: string): void {
  if (!isTenantSchemaName(name)) {
    throw new Error(`Invalid tenant schema name: ${JSON.stringify(name)}`);
  }
}

/**
 * Run `fn` on an already checked-out client inside one transaction whose
 * search path is the tenant schema for that transaction only.
 */
export async function inTenantTransaction<T>(
  client: PoolClient,
  schema: string,
  fn: (tx: PoolClient) => Promise<T>,
  options: { lockTimeout?: string } = {},
): Promise<T> {
  assertTenantSchemaName(schema);
  await client.query("begin");
  try {
    // `set_config(..., true)` is transaction-local: gone at COMMIT or ROLLBACK,
    // so a pooled connection never carries a tenant into its next use.
    await client.query("select set_config('search_path', $1, true)", [schema]);
    if (options.lockTimeout) {
      // DDL waits at most this long for a lock instead of queueing behind live traffic.
      await client.query("select set_config('lock_timeout', $1, true)", [options.lockTimeout]);
    }
    const result = await fn(client);
    await client.query("commit");
    return result;
  } catch (err) {
    await client.query("rollback").catch(() => undefined);
    throw err;
  }
}

/**
 * Run `fn` inside one transaction whose search path is the tenant schema.
 * Safe through node-postgres pools and PgBouncer in transaction mode.
 * See ADR 0006 and docs/research/schema-per-tenant-feasibility.md.
 */
export async function withTenant<T>(
  pool: Pool,
  schema: string,
  fn: (tx: PoolClient) => Promise<T>,
): Promise<T> {
  assertTenantSchemaName(schema);
  const client = await pool.connect();
  let broken: Error | undefined;
  try {
    return await inTenantTransaction(client, schema, fn);
  } catch (err) {
    broken = err instanceof Error ? err : new Error(String(err));
    throw err;
  } finally {
    // Passing an error tells the pool to discard the connection instead of reusing it.
    client.release(broken);
  }
}
